#!/bin/bash
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

php artisan key:generate

echo "-----------------------"
echo "limpiando cache de config"
echo "-----------------------"
php artisan config:clear

echo "-----------------------"
echo "limpiando cache de Route"
echo "-----------------------"
php artisan route:clear

echo "-----------------------"
echo "limpiando cache de view"
echo "-----------------------"
php artisan view:clear

echo "-----------------------"
echo "clear cache"
echo "-----------------------"
php artisan cache:clear

echo "-----------------------"
echo "creando cache config"
echo "-----------------------"
php artisan config:cache

echo "-----------------------"
echo "creando cache route"
echo "-----------------------"
php artisan route:cache

echo "-----------------------"
echo "creando cache view"
echo "-----------------------"
php artisan view:cache


# echo "-----------------------"
# echo "Creando Base de Datos"
# echo "-----------------------"

# php bin/console d:d:c --if-not-exists
# chmod 777 -R storage/framework/ storage/logs

 echo "-----------------------"
 echo "Corriendo Migraciones"
 echo "-----------------------"
 php artisan migrate --force
# # php artisan db:seed

exec docker-php-entrypoint "$@"
